import { Component, inject, signal, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule, FormBuilder, FormGroup, Validators, FormArray } from '@angular/forms';
import {
  IonContent, IonHeader, IonTitle, IonToolbar, IonCard, IonCardContent,
  IonCardHeader, IonCardTitle, IonButton, IonIcon, IonText, IonInput,
  IonItem, IonLabel, IonTextarea, IonSelect, IonSelectOption,
  IonBackButton, IonButtons, IonGrid, IonRow, IonCol, IonToggle,
  IonChip, IonBadge, IonList, IonReorderGroup, IonReorder,
  IonAlert, AlertController, IonToast, ToastController
} from '@ionic/angular/standalone';
import { Router } from '@angular/router';
import { addIcons } from 'ionicons';
import {
  arrowBackOutline, personAddOutline, mailOutline, sendOutline,
  addOutline, removeOutline, checkmarkCircleOutline,
  informationCircleOutline, warningOutline, copyOutline,
  shareOutline, qrCodeOutline, linkOutline
} from 'ionicons/icons';

import { FamilyService } from '../../../core/services/family/family.service';
import { InvitationService } from '../../../core/services/family/invitation.service';
import {
  InviteMemberRequest,
  FamilyRoleEnum,
  Family
} from '../../../models/families/family.models';
import { catchError, EMPTY, finalize, tap, combineLatest } from 'rxjs';

interface InviteFormData {
  email: string;
  role: FamilyRoleEnum;
  message?: string;
}

@Component({
  selector: 'app-invite-member',
  templateUrl: './invite-member.page.html',
  styleUrls: ['./invite-member.page.scss'],
  standalone: true,
  imports: [
    CommonModule, FormsModule, ReactiveFormsModule,
    IonContent, IonHeader, IonTitle, IonToolbar, IonCard, IonCardContent,
    IonCardHeader, IonCardTitle, IonButton, IonIcon, IonText, IonInput,
    IonItem, IonLabel, IonTextarea, IonSelect, IonSelectOption,
    IonBackButton, IonButtons, IonGrid, IonRow, IonCol, IonToggle,
    IonChip, IonBadge, IonList, IonReorderGroup, IonReorder
  ]
})
export class InviteMemberPage implements OnInit {
  private readonly familyService = inject(FamilyService);
  private readonly invitationService = inject(InvitationService);
  private readonly router = inject(Router);
  private readonly formBuilder = inject(FormBuilder);
  private readonly alertController = inject(AlertController);
  private readonly toastController = inject(ToastController);

  // Signals for reactive state
  isLoading = signal<boolean>(false);
  currentFamily = signal<Family | null>(null);
  isBulkMode = signal<boolean>(false);
  inviteLink = signal<string>('');

  // Forms
  singleInviteForm!: FormGroup;
  bulkInviteForm!: FormGroup;

  // Available roles for invitation
  availableRoles = [
    {
      value: FamilyRoleEnum.MEMBER,
      title: 'Member',
      description: 'Can participate in family activities',
      icon: 'person-outline',
      color: '#22c55e'
    },
    {
      value: FamilyRoleEnum.ADMIN,
      title: 'Admin',
      description: 'Can manage family settings and members',
      icon: 'shield-checkmark-outline',
      color: '#3b82f6'
    }
  ];

  constructor() {
    this.addIcons();
    this.initializeForms();
  }

  ngOnInit() {
    this.loadFamilyData();
    this.generateInviteLink();
  }

  private addIcons() {
    addIcons({
      arrowBackOutline, personAddOutline, mailOutline, sendOutline,
      addOutline, removeOutline, checkmarkCircleOutline,
      informationCircleOutline, warningOutline, copyOutline,
      shareOutline, qrCodeOutline, linkOutline
    });
  }

  private initializeForms() {
    this.singleInviteForm = this.formBuilder.group({
      email: ['', [Validators.required, Validators.email]],
      role: [FamilyRoleEnum.MEMBER, [Validators.required]],
      message: ['']
    });

    this.bulkInviteForm = this.formBuilder.group({
      invites: this.formBuilder.array([]),
      defaultRole: [FamilyRoleEnum.MEMBER],
      defaultMessage: ['']
    });
  }

  private loadFamilyData() {
    combineLatest([
      this.familyService.currentFamily$
    ]).subscribe(([family]) => {
      this.currentFamily.set(family);
    });
  }

  private generateInviteLink() {
    // This would generate a shareable family invite link
    const family = this.currentFamily();
    if (family) {
      // In a real app, this would be generated by the backend
      const baseUrl = window.location.origin;
      this.inviteLink.set(`${baseUrl}/family/join/${family.id}`);
    }
  }

  // Bulk invite methods
  get invitesArray(): FormArray {
    return this.bulkInviteForm.get('invites') as FormArray;
  }

  addInviteField() {
    const inviteGroup = this.formBuilder.group({
      email: ['', [Validators.required, Validators.email]],
      role: [this.bulkInviteForm.get('defaultRole')?.value || FamilyRoleEnum.MEMBER],
      message: [this.bulkInviteForm.get('defaultMessage')?.value || '']
    });

    this.invitesArray.push(inviteGroup);
  }

  removeInviteField(index: number) {
    this.invitesArray.removeAt(index);
  }

  toggleBulkMode() {
    this.isBulkMode.set(!this.isBulkMode());

    if (this.isBulkMode() && this.invitesArray.length === 0) {
      this.addInviteField();
    }
  }

  applyDefaultsToAll() {
    const defaultRole = this.bulkInviteForm.get('defaultRole')?.value;
    const defaultMessage = this.bulkInviteForm.get('defaultMessage')?.value;

    this.invitesArray.controls.forEach(control => {
      control.patchValue({
        role: defaultRole,
        message: defaultMessage
      });
    });
  }

  // Single invite
  onSendSingleInvite() {
    if (!this.singleInviteForm.valid) {
      this.singleInviteForm.markAllAsTouched();
      return;
    }

    const family = this.currentFamily();
    if (!family) {
      this.showToast('No family selected', 'danger');
      return;
    }

    this.isLoading.set(true);

    const formValue = this.singleInviteForm.value;
    const inviteRequest: InviteMemberRequest = {
      email: formValue.email,
      role: formValue.role,
      message: formValue.message || undefined
    };

    this.invitationService.inviteMember(family.id, inviteRequest).pipe(
      tap(async () => {
        this.singleInviteForm.reset({
          role: FamilyRoleEnum.MEMBER,
          message: ''
        });
        await this.showSuccessAlert('Invitation sent successfully!');
      }),
      catchError(error => {
        console.error('Invitation error:', error);
        return EMPTY;
      }),
      finalize(() => {
        this.isLoading.set(false);
      })
    ).subscribe();
  }

  // Bulk invite
  onSendBulkInvites() {
    if (!this.bulkInviteForm.valid) {
      this.bulkInviteForm.markAllAsTouched();
      return;
    }

    const family = this.currentFamily();
    if (!family) {
      this.showToast('No family selected', 'danger');
      return;
    }

    const invites = this.invitesArray.value.filter((invite: InviteFormData) =>
      invite.email && invite.email.trim()
    );

    if (invites.length === 0) {
      this.showToast('Please add at least one email address', 'warning');
      return;
    }

    this.isLoading.set(true);

    const inviteRequests: InviteMemberRequest[] = invites.map((invite: InviteFormData) => ({
      email: invite.email.trim(),
      role: invite.role,
      message: invite.message || undefined
    }));

    this.invitationService.inviteMultipleMembers(family.id, inviteRequests).pipe(
      tap(async () => {
        this.bulkInviteForm.reset();
        this.invitesArray.clear();
        this.isBulkMode.set(false);
        await this.showSuccessAlert(`${inviteRequests.length} invitations sent successfully!`);
      }),
      catchError(error => {
        console.error('Bulk invitation error:', error);
        return EMPTY;
      }),
      finalize(() => {
        this.isLoading.set(false);
      })
    ).subscribe();
  }

  // Share invite link
  async onCopyInviteLink() {
    try {
      await navigator.clipboard.writeText(this.inviteLink());
      await this.showToast('Invite link copied to clipboard!', 'success');
    } catch (error) {
      console.error('Failed to copy link:', error);
      await this.showToast('Failed to copy link', 'danger');
    }
  }

  async onShareInviteLink() {
    const family = this.currentFamily();
    if (!family) return;

    try {
      if (navigator.share) {
        await navigator.share({
          title: `Join ${family.name} on Family Connect`,
          text: `You've been invited to join our family on Family Connect!`,
          url: this.inviteLink()
        });
      } else {
        // Fallback to copy
        await this.onCopyInviteLink();
      }
    } catch (error) {
      console.error('Failed to share link:', error);
    }
  }

  onGenerateQRCode() {
    // TODO: Implement QR code generation
    this.showToast('QR code feature coming soon!', 'warning');
  }

  // Navigation
  onCancel() {
    this.router.navigate(['/tabs/family']);
  }

  onViewInvitations() {
    this.router.navigate(['/family/invitations']);
  }

  // Form validation helpers
  getFieldError(formGroup: FormGroup, fieldName: string): string | null {
    const field = formGroup.get(fieldName);
    if (!field || !field.touched || !field.errors) {
      return null;
    }

    const errors = field.errors;
    if (errors['required']) return `${this.getFieldDisplayName(fieldName)} is required`;
    if (errors['email']) return 'Please enter a valid email address';

    return 'Invalid value';
  }

  private getFieldDisplayName(fieldName: string): string {
    const displayNames: { [key: string]: string } = {
      email: 'Email',
      role: 'Role',
      message: 'Message'
    };
    return displayNames[fieldName] || fieldName;
  }

  hasFieldError(formGroup: FormGroup, fieldName: string): boolean {
    return !!this.getFieldError(formGroup, fieldName);
  }

  getRoleInfo(role: FamilyRoleEnum) {
    return this.availableRoles.find(r => r.value === role);
  }

  // UI helpers
  private async showToast(message: string, color: 'success' | 'danger' | 'warning' = 'success') {
    const toast = await this.toastController.create({
      message,
      duration: 3000,
      color,
      position: 'top',
      buttons: [
        {
          text: 'Dismiss',
          role: 'cancel'
        }
      ]
    });
    await toast.present();
  }

  private async showSuccessAlert(message: string) {
    const alert = await this.alertController.create({
      header: 'Success',
      message,
      buttons: [
        {
          text: 'View Invitations',
          handler: () => {
            this.onViewInvitations();
          }
        },
        {
          text: 'Send More',
          role: 'cancel'
        }
      ]
    });
    await alert.present();
  }

  // Template getters
  get canSendSingleInvite(): boolean {
    return this.singleInviteForm.valid && !this.isLoading();
  }

  get canSendBulkInvites(): boolean {
    return this.bulkInviteForm.valid && this.invitesArray.length > 0 && !this.isLoading();
  }

  get validInvitesCount(): number {
    return this.invitesArray.controls.filter(control =>
      control.get('email')?.valid
    ).length;
  }
}
